# Generated by Django 2.2.3 on 2019-07-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='built',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='built_template_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
