# Generated by Django 2.2.3 on 2019-08-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20190726_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
    ]
